name: Three Jobs Workflow
on:
  push:
    branches:
      - test2

concurrency:
  group: my-unique-concurrency-group

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1      
        run: |
          git checkout https://github.com/YurkoWasHere/GitHubActionTest.git
          cd GitHubActionTest
          git checkout test3
          echo " TEST 123  " >test3
          git add .
          git commit -m "test1"
          git push
        
