name: Three Jobs Workflow
on:
  push:
    branches:
      - test2

concurrency:
  group: my-unique-concurrency-group
  
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1      
        run: |
          set -x
          git clone https://github.com/YurkoWasHere/GitHubActionTest.git
          cd GitHubActionTest
          git checkout test3
          echo " TEST 123  " >test3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./GitHubActionTest
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
