name: Three Jobs Workflow
on:
  push:
    branches:
      - main

concurrency:
  group: my-unique-concurrency-group

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        matrix_var: [matrix_job_1_1, matrix_job_1_2, matrix_job_1_3] # Add your matrix values here
      max-parallel: 1
    steps:
      - name: Job 1
        run: echo "This is Job 1" ; sleep 120
        

  job2:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job1]
    strategy:
      matrix:
        matrix_var: [matrix_job_2_1, matrix_job_2_2, matrix_job_2_3] # Add your matrix values here
      max-parallel: 1
    steps:
      - name: Job 2
        run: echo "This is Job 2" ; sleep 120
        
  job3:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job2]
    strategy:
      matrix:
        matrix_var: [matrix_job_3_1, matrix_job_3_2, matrix_job_3_3] # Add your matrix values here
      max-parallel: 1
    steps:
      - name: Job 3
        run: echo "This is Job 3" ; sleep 120
